"""initial schema

Revision ID: 3811375a092e
Revises: 
Create Date: 2026-05-25 06:28:25.751462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3811375a092e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agents', 'balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('agents', 'frozen_balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('agents', 'total_earned',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.drop_index('idx_agents_description_vec', table_name='agents', postgresql_using='hnsw')
    op.alter_column('demands', 'publisher_type',
               existing_type=sa.VARCHAR(length=16),
               nullable=False,
               existing_server_default=sa.text("'user'::character varying"))
    op.alter_column('demands', 'fulfill_mode',
               existing_type=sa.VARCHAR(length=16),
               nullable=False,
               existing_server_default=sa.text("'auto'::character varying"))
    op.alter_column('demands', 'match_status',
               existing_type=sa.VARCHAR(length=16),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_index('idx_demands_demand_vec', table_name='demands', postgresql_using='hnsw')
    op.alter_column('orders', 'eta_hours',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('24'))
    op.alter_column('orders', 'delivery_attempts',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('orders', 'reject_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.add_column('payments', sa.Column('raw_response', sa.Text(), nullable=True))
    op.create_foreign_key('payments_user_id_fkey', 'payments', 'users', ['user_id'], ['id'])
    op.create_foreign_key('payments_order_id_fkey', 'payments', 'orders', ['order_id'], ['id'])
    op.alter_column('reviews', 'is_appealed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('withdraws', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('withdraws', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('withdraws', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('withdraws', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('withdraws', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('withdraws', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('reviews', 'is_appealed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_constraint('payments_order_id_fkey', 'payments', type_='foreignkey')
    op.drop_constraint('payments_user_id_fkey', 'payments', type_='foreignkey')
    op.drop_column('payments', 'raw_response')
    op.alter_column('orders', 'reject_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('orders', 'delivery_attempts',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('orders', 'eta_hours',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('24'))
    op.create_index('idx_demands_demand_vec', 'demands', ['demand_vec'], unique=False, postgresql_using='hnsw')
    op.alter_column('demands', 'match_status',
               existing_type=sa.VARCHAR(length=16),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('demands', 'fulfill_mode',
               existing_type=sa.VARCHAR(length=16),
               nullable=True,
               existing_server_default=sa.text("'auto'::character varying"))
    op.alter_column('demands', 'publisher_type',
               existing_type=sa.VARCHAR(length=16),
               nullable=True,
               existing_server_default=sa.text("'user'::character varying"))
    op.create_index('idx_agents_description_vec', 'agents', ['description_vec'], unique=False, postgresql_using='hnsw')
    op.alter_column('agents', 'total_earned',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('agents', 'frozen_balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('agents', 'balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    # ### end Alembic commands ###
